// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YoutubeDotNet9.Models;

#nullable disable

namespace YoutubeDotNet9.Migrations
{
    [DbContext(typeof(SampleDatabaseContext))]
    partial class SampleDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("YoutubeDotNet9.Models.Pokemon", b =>
                {
                    b.Property<int>("PokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PokedexNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PokemonId");

                    b.HasIndex("RegionId");

                    b.HasIndex("TypeId");

                    b.ToTable("Pokemon", (string)null);
                });

            modelBuilder.Entity("YoutubeDotNet9.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegionName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("RegionId");

                    b.ToTable("Region", (string)null);
                });

            modelBuilder.Entity("YoutubeDotNet9.Models.Type", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TypeId");

                    b.ToTable("Type", (string)null);
                });

            modelBuilder.Entity("YoutubeDotNet9.Models.Pokemon", b =>
                {
                    b.HasOne("YoutubeDotNet9.Models.Region", "Region")
                        .WithMany("Pokemons")
                        .HasForeignKey("RegionId")
                        .HasConstraintName("FK_Pokemon_Region");

                    b.HasOne("YoutubeDotNet9.Models.Type", "Type")
                        .WithMany("Pokemons")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Pokemon_Type");

                    b.Navigation("Region");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("YoutubeDotNet9.Models.Region", b =>
                {
                    b.Navigation("Pokemons");
                });

            modelBuilder.Entity("YoutubeDotNet9.Models.Type", b =>
                {
                    b.Navigation("Pokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
